version: "3.8"

services:
  app:
    build: .
    image: server_management:1.0.0 
    container_name: server_management
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      INFLUX_URL: ${INFLUX_URL}
      INFLUX_TOKEN: ${INFLUX_TOKEN}
      ORG: ${ORG}
      BUCKET: ${BUCKET}
      IPMI_DEVICES_FILE: ${IPMI_DEVICES_FILE}
    volumes:
      - ./IPMI_devices.json:/app/IPMI_devices.json
    restart: unless-stopped
