version: "3.8"

services:
  app:
    build: .
    image: docker.io/library/devraq-server-management:1.0.0
    imagePullPolicy: IfNotPresent
    container_name: devraq-server-management
    ports:
      - "8008:8008"
    env_file:
      - .env
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      REDFISH_BUCKET_NAME: ${REDFISH_BUCKET_NAME}
      IPMI_DEVICES_FILE: ${IPMI_DEVICES_FILE}
    volumes:
      - ./IPMI_devices.json:/app/IPMI_devices.json
    restart: unless-stopped
